<?php
$PAGE=[
    'id'=>'index',
    'title'=>'Главная',
    'body'=>file_get_contents(ROOT.'system/pages/index.html'),
    'build'=>'',
    'template'=>[
        'css'=>'/assets/css/main.css'
    ],
    'postloads'=>[
        '/assets/js/main.js'
    ]
];